config/routes.rb
Rails.application.routes.draw do
  resources :links

  get ':slug' => 'links#go_to_site'

  root 'home#index'

end

app/models/link.rb
class Link < ActiveRecord::Base
  # Validates presence of title and given_url
  validates :title, presence: { message: "Please enter title" }
  validates :given_url, presence: { message: "Please enter URL" }

  after_create :generate_short_url
  before_create :add_protocol_to_given_url

  self.per_page = 10

  # Generate short url after creating link object
  def generate_short_url
    self.shorten_url = self.id.to_s(36)
    self.save
  end

  # Add http protocol if user not added to url
  def add_protocol_to_given_url
    unless (self.given_url.start_with?('http') || self.given_url.start_with?('https'))
      self.given_url.prepend('http://')
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  # Show top 10 most visited links
  def index
    # @link = Link.new
    @links = Link.order(clicks: :desc).first(10)
  end

end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show, :edit, :update, :destroy]

  # GET /links
  # GET /links.json
  def index
    # Get list of links in descending order of clicks
    @links = Link.all.paginate(:page => params[:page]).order(clicks: :desc)
  end

  # GET /links/1
  # GET /links/1.json
  def show

  end

  # GET /links/new
  def new
    @link = Link.new
  end

  # GET /links/1/edit
  def edit
  end

  # POST /links
  # POST /links.json
  def create
    @link = Link.new(link_params)

    respond_to do |format|
      if @link.save
        format.html { redirect_to links_url, notice: 'Link was successfully created.' }
        format.json { render :show, status: :created, location: @link }
      else
        format.html { render :new }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /links/1
  # PATCH/PUT /links/1.json
  def update
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to @link, notice: 'Link was successfully updated.' }
        format.json { render :show, status: :ok, location: @link }
      else
        format.html { render :edit }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  # DELETE /links/1.json
  def destroy
    @link.destroy
    respond_to do |format|
      format.html { redirect_to links_url, notice: 'Link was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # Action which redirects to main url using short url
  def go_to_site
    @link = Link.find_by(shorten_url: params[:slug])
    if redirect_to @link.given_url
      @link.clicks += 1
      @link.save
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @link = Link.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def link_params
      params.require(:link).permit(:given_url, :title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/home/index.html.erb
<h1>TOP MOST VISITED LINKS</h1>
<%= render :partial => 'links/links' %>
<%= link_to 'All links', links_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Url Shortner by Amit</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container application-container">
  <%= yield %>
</div>

</body>
</html>

app/views/links/_form.html.erb
<%= form_for(@link) do |f| %>
  <% if @link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% @link.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :title, :class => "control-label" %>
        <%= f.text_field :title ,:class =>"form-control", :placeholder => "Paste a title for site" %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :given_url ,'URL', :class => "control-label" %>
        <%= f.text_field :given_url ,:class =>"form-control", :placeholder => "Enter a link to shorten" %>
      </div>
    </div>
  </div>
  <div class="actions">
    <%= f.submit 'Make short URL' %>
  </div>
<% end %>

app/views/links/_links.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Given url</th>
      <th>Shorten url</th>
      <th>Clicks</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @links.each do |link| %>
      <tr>
        <td><%= link.title %></td>
        <td><%= link.given_url %></td>
        <td><%= link_to BASE_URL + link.shorten_url, BASE_URL + link.shorten_url %></td>
        <td><%= link.clicks %></td>
        <td><%= link_to 'Edit', edit_link_path(link), class: "btn btn-sm btn-primary" %></td>
        <td><%= link_to 'Destroy', link, class: "btn btn-sm btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/links/edit.html.erb
<h1>Editing Link</h1>

<%= render 'form' %>

<%= link_to 'Show', @link %> |
<%= link_to 'Back', links_path %>

app/views/links/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Total Links</h1>

<%= render :partial => 'links/links' %>
<div class="digg_pagination">
  <%= will_paginate @links %>
</div>

<br>

<%= link_to 'New Link', new_link_path %> |
<%= link_to 'Top links', root_path %>

app/views/links/new.html.erb
<h1>Enter a link to shorten</h1>

<%= render 'form' %>

<%= link_to 'Back', links_path %>

app/views/links/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Given url:</strong>
  <%= @link.given_url %>
</p>

<p>
  <strong>Shorten url:</strong>
  <%= @link.shorten_url %>
</p>

<p>
  <strong>Clicks:</strong>
  <%= @link.clicks %>
</p>

<p>
  <strong>Title:</strong>
  <%= @link.title %>
</p>

<%= link_to 'Edit', edit_link_path(@link) %> |
<%= link_to 'Back', links_path %>